// Code generated by "stringer -type=Enum -linecomment"; DO NOT EDIT.

package stringer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-1]
	_ = x[Fail-2]
	_ = x[Unknow-3]
}

const _Enum_name = "successfailunknow"

var _Enum_index = [...]uint8{0, 7, 11, 17}

func (i Enum) String() string {
	i -= 1
	if i >= Enum(len(_Enum_index)-1) {
		return "Enum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Enum_name[_Enum_index[i]:_Enum_index[i+1]]
}
